In [26]:
import pickle
import numpy as np

In [27]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [28]:
test_input_sex = ohe_sex.fit_transform(test_input[:,1].reshape(1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
clf.fit(test_input_sex,test_input_embarked)
clf.predict(test_input_sex)


array([[0., 0., 1.]])

In [29]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [49]:
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [44]:
test_input

array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object)

In [50]:
pipe.fit(test_input[:,0:7],test_input[:,-1])


ValueError: could not convert string to float: 'male'